### PR TITLE
Added workaround and logger warning for missing parameter issue disco…

### PR DESCRIPTION
**Pull request by james-strauss-uwa**
…vered when processing rascil codebase

### CODE REVIEW

**Review by awicenec — CHANGES_REQUESTED** [review]
Which RASCIL function caused this? We should add it to the tests. If you give me the pointer I will do it since I have a few other changes to merge as well.

**Comment by james-strauss-uwa** [comment]
Here is the log from a successful local run:

`22-Dec-22T00:05:26 [  xml2palette.py  ] [  1459  ] [  params_to_nodes  ] || Adding component: calculate_noise_visibility ||
22-Dec-22T00:05:26 [  xml2palette.py  ] [  1459  ] [  params_to_nodes  ] || Adding component: addnoise_visibility ||
22-Dec-22T00:05:26 [  xml2palette.py  ] [  930  ] [  _process_rEST  ] || No parameter named pt found in parameter dictionary. Known parameters are: pointing_error, static_pointing_error, global_pointing_error, kwargs ||
22-Dec-22T00:05:26 [  xml2palette.py  ] [  1459  ] [  params_to_nodes  ] || Adding component: simulate_gaintable_from_pointingtable ||
22-Dec-22T00:05:26 [  xml2palette.py  ] [  1459  ] [  params_to_nodes  ] || Adding component: simulate_pointingtable ||
22-Dec-22T00:05:26 [  xml2palette.py  ] [  1459  ] [  params_to_nodes  ] || Adding component: simulate_pointingtable_from_timeseries ||`

It looks like the function was either "addnoise_visibility" or "simulate_gametable_from_pointingtable", and the particular parameter is named "pt".

**Comment by awicenec** [comment]
I have incorporated this change already into main along with all my other changes. Could you please try release 0.1.4?

**Comment by james-strauss-uwa** [comment]
Release 0.1.4 fixed the problem. I'm now seeing a different problem:

Traceback (most recent call last):
  File "/builds/ska-telescope/ska-sdp-daliuge-palette-generator/venv/bin/dlg_paletteGen", line 8, in <module>
    sys.exit(main())
  File "/builds/ska-telescope/ska-sdp-daliuge-palette-generator/venv/lib/python3.9/site-packages/dlg_paletteGen/cli.py", line 248, in main
    functions = process_compounddef_default(compounddef, language)
  File "/builds/ska-telescope/ska-sdp-daliuge-palette-generator/venv/lib/python3.9/site-packages/dlg_paletteGen/base.py", line 1572, in process_compounddef_default
    cdescrObj = Child(tchild, language, parent=compound)
  File "/builds/ska-telescope/ska-sdp-daliuge-palette-generator/venv/lib/python3.9/site-packages/dlg_paletteGen/base.py", line 1404, in __init__
    ddO = DetailedDescription(dStr)
  File "/builds/ska-telescope/ska-sdp-daliuge-palette-generator/venv/lib/python3.9/site-packages/dlg_paletteGen/base.py", line 833, in __init__
    self._identify_format()
  File "/builds/ska-telescope/ska-sdp-daliuge-palette-generator/venv/lib/python3.9/site-packages/dlg_paletteGen/base.py", line 1073, in _identify_format
    dd = self.description.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by awicenec** [comment]
Closing this off, since it was merged with another branch and then back into master. Is all in release 0.14

**Pull request closed without merging**
